### ISSUE TITLE
Geocomplete field error trim(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by lerc90Mzl** [cheesegrits/filament-google-maps#44] opened 2023-09-04 22:43 UTC
Hi, I'm using the Geocomplete component and when I choose some location appears  de error "trim(): Argument #1 ($string) must be of type string, array given", I need to save lat and lng, the problem is in the class  ComponentAttributeBag.php, the method  __toString() expects a string value but the component return an array(lat and lng)

Geocomplete::make('location')
                  ->isLocation()
                  ->reverseGeocode([
                      'city'   => '%L',
                      'zip'    => '%z',
                      'state'  => '%A1',
                      'street' => '%n %S',
                  ])
                  ->countries(['us','co'])
                  ->updateLatLng()
                  ->maxLength(1024)
                  ->prefix('Choose:')
                  ->placeholder('Start typing an address ...')
                  ->geolocate() 
                  ->geolocateIcon('heroicon-o-map')
                  ->required(),

Proyect info: Laravel 10.21, filament v3

Thanks for the pluggin!!

![trim error](https://github.com/cheesegrits/filament-google-maps/assets/144069997/5dd47392-709b-47d4-bd1a-04025e7cd6b1)

**Comment by alazark94** [comment] 2023-09-06 06:57
Hello, Having the same issue here.

**Comment by elbaylot** [comment] 2023-09-07 08:25
Same here

**Comment by cheesegrits** [comment] 2023-09-11 19:12
Looking at this issue now.

BTW, quickest way to get hold of me is in the #google-maps channel on the Filament Discord.

**Comment by cheesegrits** [comment] 2023-09-11 21:34
OK, I think I've fixed this.  It was a regression caused by a recent change in Filament v3.

I need to add some more tests to the test suite and make sure my fix hasn't broken anything else, then I'll push a new version.

**Comment by cheesegrits** [comment] 2023-09-11 22:38
Should be fixed in v3.0.5

**Closed by cheesegrits** 2023-09-11 22:38 UTC

**Comment by lerc90Mzl** [comment] 2023-09-11 22:47
Thank you, I will update my proyect to v3.0.5
